### ISSUE TITLE
`System.DllNotFoundException´ in rcldotnet_common.dll

### ISSUE THREAD

**Issue by MischaRo** [IntelligentRoboticsLabs/ARViz#1]
Hi @dvargasfr
I tried out your Unity solution, but unfortunately it did not work for me.

I Used Unity 2018.2.91f,
 the `ros2-dotnet-uwp-x84` prebuild release from ros2_dotnet (https://github.com/esteve/ros2_dotnet/releases),
and the Hololens Emulator to test it.

I encountered a deviation from the instruction when I tried to add the reference to the `rcldotnet_assemblies.dll`, `rcldotnet_common.dll` and the `std_msgs_assemblies.dll`.
I got an error message telling me that the references cant be included, because they already exist.

![reference exists](https://user-images.githubusercontent.com/26136476/51739565-19b33600-2092-11e9-8059-86e03712e8bd.JPG)

After starting the Hololens Emulator, the application was terminated due to an System.DllNotFoundException in rcldotnet_common.dll
![rlsdotnet not found](https://user-images.githubusercontent.com/26136476/51739582-246dcb00-2092-11e9-9aa2-1485ae4c501d.JPG)

I tried adding the`rcldotnet_assemblies.dll`, `rcldotnet_common.dll` and the `std_msgs_assemblies.dll` to the project as well but that did not change anything

**Comment by dvargasfr** [comment]
> the ros2-dotnet-uwp-x84 prebuild release from ros2_dotnet 

x86 or x64? I hope you mean x86 :)

> I got an error message telling me that the references cant be included, because they already exist.

Ok, these references already exist on the VS solution generated from Unity, but they are referencing files from an `Unprocessed` folder. Just after including `rcldotnet_assemblies.dll`, `rcldotnet_common.dll` and `std_msgs_assemblies.dll` check if the references still point to `Unprocessed`files or are updated to the new DLLs added. If not updated, remove those three references and add them again.

**Comment by MischaRo** [comment]
> x86 or x64? I hope you mean x86 :)

Yeah sorry, my bad, I ment x86 :)

Alright, so I got a little farther, but the problems are still not completely solved.
This is the script, that I attached to a Game Object in Unity:
```
using UnityEngine;
using ROS2;
public class Ros2Test : MonoBehaviour

{
    string[] args;
    void Start()
    {
        //RCLDotnetTalker.Main(args);
        RCLdotnet.Init();
        INode node = RCLdotnet.CreateNode("listener");
        RCLdotnet.Spin(node);
    }
}
```
Just as basic as possible…
When I run the Hololens Emulator, the application starts, but it still gives me an System.DllNotFoundException in rcldotnet_common.dll exception

![rlsdotnet not found2](https://user-images.githubusercontent.com/26136476/51750501-8ccca480-20b2-11e9-91e1-de6d765f7e51.JPG)

Since there seems to be an UnsatisfiedLinkError, does that mean that there are some dlls missing?

**Comment by dvargasfr** [comment]
Hi @MischaRo 

Sorry for such a late response, my last days have been quite busy.

I tested your script using the `ros2-dotnet-uwp-x84` prebuild release from ros2_dotnet and also using my ros2-dotnet-uwp-x86 newest build, and it fails both times. 

I use this script:

```
using System.Collections;
using System.Collections.Generic;
using UnityEngine;

using ROS2;
using ROS2.Utils;

public class ROS2Talker : MonoBehaviour
{

    private int cont = 0;
    private IPublisher<std_msgs.msg.String> chatter_pub;
    private INode node;

    void Start()
    {
        RCLdotnet.Init();
        node = RCLdotnet.CreateNode("talker");
        chatter_pub = node.CreatePublisher<std_msgs.msg.String>("chatter");
    }

    void Update()
    {
        if (RCLdotnet.Ok())
        {
            std_msgs.msg.String msg = new std_msgs.msg.String();
            msg.Data = "Hello World: " + cont++;
            chatter_pub.Publish(msg);
        }
    }

    public void Button_Click()
    {
        if (RCLdotnet.Ok())
        {
            std_msgs.msg.String msg = new std_msgs.msg.String();
            msg.Data = "Hello World: " + cont++;
            chatter_pub.Publish(msg);
        }
    }
}
```

I tested it with `ros2-dotnet-uwp-x84` prebuild release from ros2_dotnet and also get some dysfunctional things. While I check this, could you test the prebuild binaries I recently released?
Maybe you will get some warnings but you should be able to list ros2 node/topic created and get many `Hello World` messages.

![hello_world_ros2](https://user-images.githubusercontent.com/17497748/52521750-4b282600-2c7c-11e9-8815-f02ede39e608.png)

**Comment by esteve** [comment]
@MischaRo could you open this ticket on the ros2_dotnet repo, it'll be easier for me to help you out there other users, but also to have it as a reference in case someone else has the same problem.

@dvargasfr please don't package your ros2_dotnet workspace and call it a release, it's really confusing and misleading for everyone who wants to use ros2_dotnet
